# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# AppStore
KEY_FILE_PATH = "YOUR_KEY_FILE_PATH"
KEY_ID = "YOUR_KEY_ID"
ISSUER_ID = "YOUR_ISSUER_ID"
WORKSPACE_PATH = " Petcare-iOS.xcodeproj/project.xcworkspace"
TARGET_SCHEME = "Petcare-iOS"
CONFIG_APPSTORE = "Release"
OUTPUT_DIRECTORY = "./fastlane/builds"



default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
